export const COLOR = {
    BACKCOLOR: "#000000",
    FONTCOLOR_WHITE: "#FFFFFF",
    INPUTBOX_GRAY:"#534949",
    MAIN_COLOR_GREEN:"#29DAA3",
    PLACEHOLDER_WHITE: '#A7A7A7',
    ERROR_RED:"#FF3E3E"
}